# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
builds:
  - env:
      - CGO_ENABLED=0
    goarch:
      - amd64
      - arm64
      - ppc64le
      - s390x
    dir: ./cmd/k8s-netperf/
archives:
  - name_template: "k8s-netperf-{{.Arch}}"
    format: tar.gz
    format_overrides:
    - goos: windows
      format: zip
    replacements:
      386: i386
      amd64: x86_64
    files:
      - LICENSE
