name: Release Go project

on:
  push:
    tags:
      - "*" # triggers only if push new tag version

env:
  CONTAINER_REGISTRY: ${{ github.repository_owner == 'cloud-bulldozer' && 'quay.io' }}
  RHEL_VERSION: ubi9
  GO_VER: 1.19

jobs:
  build-binaries:
    name: GoReleaser build
    runs-on: ubuntu-latest

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go ${{ env.GO_VER }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VER }}
        id: go

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@master
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}

  build-and-push-container-images:
    name: Build and Push Container Images
    runs-on: <IMAGE_NAME>

    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2

      - name: Setup docker-buildx
        uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: --debug
          config-inline: |
            [worker.oci]
              max-parallelism = 1

      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to the ${{ env.CONTAINER_REGISTRY }} Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.CONTAINER_REGISTRY }}
          username: ${{ env.CONTAINER_REGISTRY == 'quay.io' && secrets.QUAY_IO_USERNAME || github.actor }}
          password: ${{ env.CONTAINER_REGISTRY == 'quay.io' && secrets.QUAY_IO_TOKEN    || secrets.GITHUB_TOKEN }

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.CONTAINER_REGISTRY }}/${{ github.repository_owner }}/netperf
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}.{{minor}}.{{patch}}

      - name: Build and push multi-arch Image
        id: push
        uses: docker/build-push-action@v3
        with:
          context: ${{ matrix.CONTEXT }}
          file: containers/Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          push: ${{ github.event_name != 'pull_request' }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            RHEL_VERSION=${{ env.RHEL_VERSION }}
            GO_VER=${{ env.GO_VER }}
            GO_TAGS=