name: Release Go project

on:
  push:
    tags:
      - "*" # triggers only if push new tag version

env:
  CONTAINER_REGISTRY: ${{ github.repository_owner == 'cloud-bulldozer' && 'quay.io' }}
  GO_VER: 1.19

jobs:
  build-binaries:
    name: GoReleaser build
    runs-on: ubuntu-latest

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go ${{ env.GO_VER }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VER }}
        id: go

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@master
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
